version: 0.2

env:
  variables:
    ENVIRONMENT: test
    TF_IN_AUTOMATION: 1
    TERRAFORM_VERSION: 1.2.2
    BASE_PATH: terraform/modules

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo Starting install command
      - ./${BASE_PATH}/install.sh
  pre_build:
    commands:
      - echo Starting pre-build...
      - ./${BASE_PATH}/prebuild.sh
  build:
    commands:
      - echo Starting build
      - ./${BASE_PATH}/tflint.sh
  post_build:
    commands:
      - echo Test Performed completed on `date`

reports:
  Linter-reports:
    files:
      - "**/*.xml"
    base-directory: "terraform/modules/cict"
    discard-paths: no

artifacts:
  files:
      - "**/*.xml"
  name: reports
  base-directory: "terraform/modules/cict"
  discard-paths: no